site_formation/home/urls.py
from django.urls import path
from . import views


app_name='home'

urlpatterns = [
    path('',views.home,name='home'),

]

site_formation/site_formation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import  settings
from django.conf.urls.static import static


urlpatterns = [

    path('',include('home.urls')),
    path('training/',include('training.urls')),
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('billing/',include('billing.urls')),
    path('teacher/', include('teacher.urls')),
    path('payment/',include('payment.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

site_formation/teacher/urls.py
from django.urls import path
from . import views

app_name='teacher'

urlpatterns =[
    path('my_courses_teacher/', views.session_teacher, name='courses_teacher'),
    path('training_student/<int:id_session>',views.training_student,name='training_student'),
    path('list_attendance/<int:id_session>',views.list_attendance, name='list_attendance'),
    path('list_assessment/<int:id_session>',views.list_assessment,name='list_assessment'),
    path('save_attendance/',views.save_attendance, name='save_attendance'),
    path('list_attendance_date_change',views.list_attendance_date_change,name='list_attendance_date_change'),
    path('save_assessment/',views.save_assessment,name='save_assessment'),


]

site_formation/teacher/models.py
from django.db import models
from django.db.models.signals import post_save
from account.models import Profile
from training.models import Session
from booking.models import RegistrationSession
from django.dispatch import receiver
from datetime import date, datetime, timedelta
from django.core.validators import MaxValueValidator, MinValueValidator

class Attendance(models.Model):
    session=models.ForeignKey(Session,on_delete=models.CASCADE)
    date_of_attendance=models.DateField(verbose_name="Date de présence")
    ATTENDANCE_CHOICES = (
        (1, 'Présent'),
        (2, 'Absent'),
        (3, 'Absence justifiée'),
        (4, 'Absence non justifiée'),
    )

    attendance_choices = models.PositiveSmallIntegerField(choices=ATTENDANCE_CHOICES, default=2, verbose_name='Présence')
    student= models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='Etudiant',
                                limit_choices_to={'user_type': 1}, default=1)

    class Meta:
        verbose_name='Présence'
        verbose_name_plural='Présences'

    def __str__(self):
        return self.session.__str__() +'--' +str(self.date_of_attendance)


class Assessment(models.Model):
    session=models.ForeignKey(Session,on_delete=models.CASCADE)
    student = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='Etudiant',
                                limit_choices_to={'user_type': 1}, default=1)
    assessment=models.PositiveSmallIntegerField(default=0,verbose_name='Evaluation',validators=[MinValueValidator(0), MaxValueValidator(100)])




    class Meta:
        verbose_name='Evaluation'
        verbose_name_plural='Evaluations'

site_formation/teacher/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404, HttpResponse
from training.models import Session
from booking.models import RegistrationSession
from teacher.models import Attendance, Assessment
from account.models import Profile
from django.views.decorators.csrf import csrf_exempt
import json
from django.core import serializers
from django.http import JsonResponse
from datetime import datetime
from django.contrib.auth.decorators import login_required


@login_required(login_url='/account/login/')
def session_teacher(request):
    teacher=request.user.profile
    session_teacher=get_list_or_404(Session.objects.filter(teacher=teacher))
    return render(request,'teacher/my_courses_teacher.html',{'session_teacher':session_teacher})

@login_required(login_url='/account/login/')
def training_student(request,id_session):
    teacher = request.user.profile
    test_session = get_object_or_404(Session.objects.filter(teacher=teacher, id=id_session))
    registrations = get_list_or_404(RegistrationSession.objects.filter(session=id_session, status=2))
    return render(request,'teacher/list_students.html',{'registrations':registrations})



@login_required(login_url='/account/login/')
def list_attendance(request,id_session):
    teacher=request.user.profile
    session = get_object_or_404(Session.objects.filter(teacher=teacher, id=id_session))

    if Attendance.objects.filter(session=session,date_of_attendance=session.date_of_begin).exists():
        attendances = get_list_or_404(Attendance.objects.filter(session=id_session,
                                                                date_of_attendance=session.date_of_begin))
    else:
        attendances=get_list_or_404(RegistrationSession.objects.filter(session=session,status=2))
    return render(request,'teacher/list_attendance.html',{'attendances':attendances,'session':session})



@csrf_exempt
@login_required(login_url='/account/login/')
def list_attendance_date_change(request):

    if request.is_ajax():
        date_selected=request.POST['date_selected']
        id_session=request.POST['session']
        session=get_object_or_404(Session.objects.filter(id=id_session))

        if Attendance.objects.filter(session=session,date_of_attendance=date_selected).exists():
            attendances=get_list_or_404(Attendance.objects.filter(session=session,date_of_attendance=date_selected))
            list=[]
            for attendance in attendances:
                list.append({
                    'id_student':attendance.student.user.id,
                    'last_name':attendance.student.user.last_name,
                    'first_name':attendance.student.user.first_name,
                    'birth_date':attendance.student.birth_date,
                    'attendance':attendance.attendance_choices
                })


        else:
            attendances=get_list_or_404(RegistrationSession.objects.filter(session=session,status=2))
            list=[]
            for attendance in attendances:
                list.append({

                    'id_student': attendance.student.user.id,
                    'last_name': attendance.student.user.last_name,
                    'first_name': attendance.student.user.first_name,
                    'birth_date': attendance.student.birth_date,
                    'attendance': 2
                })


    print(list)
    return JsonResponse(list,safe=False)



@login_required(login_url='/account/login/')
def list_assessment(request,id_session):
    teacher=request.user.profile
    session = get_object_or_404(Session.objects.filter(teacher=teacher, id=id_session))


    if Assessment.objects.filter(session=session).exists():
        assessments=get_list_or_404(Assessment.objects.filter(session=session))
    else:
        assessments=get_list_or_404(RegistrationSession.objects.filter(session=session,status=2))
    return render(request,'teacher/list_assessment.html',{'assessments':assessments,'session':session})

@csrf_exempt
@login_required(login_url='/account/login/')
def save_attendance(request):

    data = {
        'exist': False,
        'message':'Les présences ont été réalisées avec succès !'
    }

    post=request.POST['pTableData']
    list_attendance=json.loads(post)
    date=list_attendance[0]['date']
    fdate=datetime.strptime(date, "%Y-%m-%d").date()
    id_session=list_attendance[0]['session']
    session=Session.objects.get(id=id_session)
    if Attendance.objects.filter(session=id_session,date_of_attendance=date).exists():
        data['exist']=True
        data['message']='les présences ont déja été réalisées pour le ' \
                        + list_attendance[0]['date'] + "Veuillez contacter l'administrateur " \
                                                       "pour une modification."

    elif    fdate < session.date_of_begin or fdate > session.date_of_finish:

            data['exist'] = True
            data['message'] = 'La date doit être comprise entre le début et la fin de la session.'

    else:

        for attendance in list_attendance:
            student=Profile.objects.get(user_id=attendance['id_client'],user_type=1)
            attendance_value=attendance['attendance']

            Attendance.objects.create(session=session,
                                      date_of_attendance=date,
                                      attendance_choices=attendance_value,
                                      student=student)
    return JsonResponse(data)

@csrf_exempt
@login_required(login_url='/account/login/')
def save_assessment(request):

    data={
        'exist':False,
        'message':'Les notes ont été enregistrées avec succès !'
    }

    post = request.POST['tableAssessment']
    list_assessment = json.loads(post)
    id_session=list_assessment[0]['session']
    session=Session.objects.get(id=id_session)

    if Assessment.objects.filter(session=session).exists():

        for assessment in list_assessment:
            student=Profile.objects.get(user_id=assessment['id_client'],user_type=1)
            assessment_value=assessment['assessment']
            Assessment.objects.filter(session=session, student=student).update(assessment=assessment_value)


            data['exist']=True,
            data['message']= 'Les notes ont été modifiées avec succès !'


    else:
        for assessment in list_assessment:
            student=Profile.objects.get(user_id=assessment['id_client'],user_type=1)
            assessment_value=assessment['assessment']
            Assessment.objects.create(session=session, student=student,assessment=assessment_value)





    return JsonResponse(data)

site_formation/teacher/templates/teacher/assessment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block content %}

     <form method="POST" class="attendance-form">{% csrf_token %}
        <div class="container">
            <h4>Evaluation</h4>


            <div class="form-group">
                <label for="num_session">Session n°</label>
                <input type="text" class="form-control" id="num_session" value="{{ session.id }}">
                <label for="name_training">Formation</label>
                <input type="text" class="form-control" id="name_training" value="{{ session.training.name }}">
                <label for="date_of_begin">Date de début</label>
                <input type="text" class="form-control" id="date_of_begin" value="{{ session.date_of_begin }}">
                <label for="date_of_finish">Date de fin</label>
                <input type="text" class="form-control" id="date_of_finish" value="{{ session.date_of_finish }}">

            </div>





            <table class="table table-striped" id="table_attendance">
                  <thead>
                    <tr>
                      <th scope="col">N° étudiant</th>
                      <th scope="col">Nom</th>
                      <th scope="col">Prénom</th>
                      <th scope="col">Date de naissance</th>
                      <th scope="col">Note</th>
                    </tr>
                  </thead>
                  <tbody>
                        {% for assessment assessments %}

                            <tr>
                                <td>{{assessment.student.user.id}}</td>
                                <td>{{assessment.student.user.last_name}}</td>
                                <td>{{assessment.student.user.first_name}}</td>
                                <td>{{assessment.student.birth_date}}</td>
                                <td>
                                    <label class="assessment_label">
                                        <input id="assessment_id" type="number"><strong><p>/100</p></strong>
                                    </label>

                                </td>

                            </tr>

                        {% endfor %}
                  </tbody>
            </table>
            <button type="submit" id="save_attendance" class="btn btn-success">Enregistrer présences</button>
        </div>


    </form>


{% endblock content %}

site_formation/teacher/templates/teacher/list_assessment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block content %}

     <form method="POST" class="assessment-form">{% csrf_token %}
        <div class="container">
            <h4>Evaluation</h4>


            <div class="form-group">
                <label for="num_session">Session n°</label>
                <input type="text" class="form-control" id="num_session" value="{{ session.id }}">
                <label for="name_training">Formation</label>
                <input type="text" class="form-control" id="name_training" value="{{ session.training.name }}">
                <label for="date_of_begin">Date de début</label>
                <input type="text" class="form-control" id="date_of_begin" value="{{ session.date_of_begin }}">
                <label for="date_of_finish">Date de fin</label>
                <input type="text" class="form-control" id="date_of_finish" value="{{ session.date_of_finish }}">

            </div>





            <table class="table table-striped" id="table_assessment">
                  <thead>
                    <tr>
                      <th scope="col">N° étudiant</th>
                      <th scope="col">Nom</th>
                      <th scope="col">Prénom</th>
                      <th scope="col">Date de naissance</th>
                      <th scope="col">Note</th>
                    </tr>
                  </thead>
                  <tbody>
                        {% for assessment in assessments %}

                            <tr>
                                <td class="id_student">{{assessment.student.user.id}}</td>
                                <td class="last_name">{{assessment.student.user.last_name}}</td>
                                <td class="first_name">{{assessment.student.user.first_name}}</td>
                                <td class="birth_date">{{assessment.student.birth_date}}</td>
                                <td class="assessment">
                                    <input  type="number" class="assessment" value="{{assessment.assessment}}" min="0" max="100">
                                    <strong><span>/100</span></strong>

                                </td>

                            </tr>

                        {% endfor %}
                  </tbody>
                  <tfoot>

                  </tfoot>
            </table>
            <button type="submit" id="save_assessment" class="btn btn-success">Enregistrer notes</button>
        </div>
    </form>


{% endblock content %}

    {% block jquery %}
         <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
         <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-json/2.6.0/jquery.json.min.js"></script>
         <script src="{% static 'teacher/js/assessment.js' %}"></script>
    {% endblock jquery %}

site_formation/teacher/templates/teacher/list_attendance.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block content %}

     <form method="POST" class="attendance-form">{% csrf_token %}
        <div class="container">
            <h4>Liste des pésences</h4>


            <div class="form-group">
                <label for="num_session">Session n°</label>
                <input type="text" class="form-control" id="num_session" disabled="disabled" value="{{ session.id }}">
                <label for="name_training">Formation</label>
                <input type="text" class="form-control" id="name_training" disabled="disabled" value="{{ session.training.name }}">
                <label for="date_of_begin">Date de début</label>
                <input type="text" class="form-control" id="date_of_begin" disabled="disabled" value="{{ session.date_of_begin }}">
                <label for="date_of_finish">Date de fin</label>
                <input type="text" class="form-control" id="date_of_finish" disabled="disabled" value="{{ session.date_of_finish }}">
                <label for="date_attendance">Date de présence:</label>
                <input type="date" id="date_attendance" name="trip-start"
                       value="{{session.date_of_begin|date:'Y-m-d'}}" min="{{ session.date_of_begin|date:'Y-m-d' }}" max="{{ session.date_of_finish|date:'Y-m-d'}}">
            </div>





            <table class="table table-striped" id="table_attendance">
                  <thead>
                    <tr>
                      <th scope="col">N° étudiant</th>
                      <th scope="col">Nom</th>
                      <th scope="col">Prénom</th>
                      <th scope="col">Date de naissance</th>
                      <th scope="col">Présence</th>
                    </tr>
                  </thead>
                  <tbody id="body_attendance">
                        {% for attendance in attendances %}

                            <tr id="tr-{{attendance.student.user.id}}">
                                <td class="id_student">{{attendance.student.user.id}}</td>
                                <td class="last_name">{{attendance.student.user.last_name}}</td>
                                <td class="first_name">{{attendance.student.user.first_name}}</td>
                                <td class="birth_date">{{attendance.student.birth_date}}</td>
                                <td class="attendance">

                                    <input id="check_attendance-{{attendance.student.user.id}}" type="checkbox"
                                    {% if attendance.attendance_choices == 1 %}
                                           checked
                                    {% endif %}
                                    >


                                </td>

                            </tr>

                        {% endfor %}
                  </tbody>
            </table>
            <button type="submit" id="save_attendance" class="btn btn-success">Enregistrer présences</button>
        </div>


    </form>


{% endblock content %}

    {% block jquery %}
         <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
         <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-json/2.6.0/jquery.json.min.js"></script>
         <script src="{% static 'teacher/js/attendance.js' %}"></script>
    {% endblock jquery %}

site_formation/teacher/templates/teacher/list_students.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <h4>Liste des participants</h4>
        <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">Nom</th>
                  <th scope="col">Prenom</th>
                  <th scope="col">Date de naissance</th>
                </tr>
              </thead>
              <tbody>
                    {% for registration in registrations  %}
                        <tr>
                            <td>{{registration.student.user.last_name}}</td>
                            <td>{{registration.student.user.first_name}}</td>
                            <td>{{registration.student.birth_date}}</td>
                        </tr>
                    {% empty %}
                        <tr>
                          <td colspan="7" class="text-center bg-warning">Pas d'etudiants !</td>
                        </tr>

                    {% endfor%}
              </tbody>
        </table>

{% endblock content %}

site_formation/teacher/templates/teacher/my_courses_teacher.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <h4>Mes cours</h4>
    <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">Formations</th>
              <th scope="col">Date de début</th>
              <th scope="col">Date de fin</th>
              <th scope="col">Participants</th>
              <th scope="col">Présences</th>
              <th scope="col">Evaluations</th>
            </tr>
          </thead>
          <tbody>
                {% for session in session_teacher  %}
                    <tr>
                        <form class="show_list" method="POST" action="{% url 'teacher:training_student' id_session=session.pk %}">
                            {% csrf_token %}
                            <td>{{session.training}}</td>
                            <td>{{session.date_of_begin}}</td>
                            <td>{{session.date_of_finish}}</td>
                            <td><input type="submit" class="btn btn-danger" value="Liste des participants"></td>
                            <td><a href="{% url 'teacher:list_attendance' id_session=session.pk %}">Présences</a></td>
                            <td><a href="{% url 'teacher:list_assessment' id_session=session.pk %}">Evaluations</a></td>
                        </form>

                    </tr>

                {% endfor%}
          </tbody>
    </table>

{% endblock content%}