site_formation/home/urls.py
from django.urls import path
from . import views


app_name='home'

urlpatterns = [
    path('',views.home,name='home'),

]

site_formation/site_formation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import  settings
from django.conf.urls.static import static


urlpatterns = [

    path('',include('home.urls')),
    path('training/',include('training.urls')),
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('billing/',include('billing.urls')),
    path('teacher/', include('teacher.urls')),
    path('payment/',include('payment.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

site_formation/teacher/urls.py
from django.urls import path
from . import views

app_name='teacher'

urlpatterns =[
    path('my_courses_teacher/', views.session_teacher, name='courses_teacher'),
    path('training_student/<int:id_session>',views.training_student,name='training_student'),
    path('list_attendance/<int:id_session>',views.list_attendance, name='list_attendance'),
    path('list_assessment/<int:id_session>',views.list_assessment,name='list_assessment'),
    path('save_attendance/',views.save_attendance, name='save_attendance'),
    path('list_attendance_date_change',views.list_attendance_date_change,name='list_attendance_date_change'),
    path('save_assessment/',views.save_assessment,name='save_assessment'),


]

site_formation/training/urls.py
from django.urls import path
from . import views

app_name='training'

urlpatterns = [

    path('',views.TrainingListView.as_view(),name='list_training'),
    path('<int:id>/',views.training_detail,name='detail_training'),
    path('my_training/',views.my_training,name='my_training'),
    path('update_registration/<int:id_registration>/',views.update_registration,name='update_registration'),
]

site_formation/templates/base.html
<!DOCTYPE html>
<html lang="fr">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Gestion de formations en ligne">
  <meta name="author" content="Zaidani Adel">

  <title>Gestion de formations en ligne</title>
{% load static %}
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="{% static 'css/index.css' %}" rel="stylesheet">
  {% block head %} {% endblock head %}
</head>

<body>
  {% include 'nav.html'%}

  {% block header %}

  {% endblock header %}

  <div class="container">
   {% block content %}

   {% endblock content%}


  </div>


   <!-- Footer -->
  <footer class="footer py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Gestion formations 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'jquery/jquery.min.js' %}"></script>
  <script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>
  {% block jquery %}
  {% endblock jquery %}
  {% block script %}
  {% endblock script %}

</body>

</html>

site_formation/templates/index.html
<!DOCTYPE html>
<html lang="fr">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Gestion de formations en ligne">
  <meta name="author" content="Zaidani Adel">

  <title>Gestion de formations en ligne</title>
{% load static %}
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="{% static 'css/index.css' %}" rel="stylesheet">
  {% block head %} {% endblock head %}
</head>

<body>
  {% include 'nav.html'%}

  {% block header %}

  {% endblock header %}

  <div class="container">
   {% block content %}

   {% endblock content%}


  </div>


   <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Gestion formations 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'jquery/jquery.min.js' %}"></script>
  <script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>
  {% block jquery %}
  {% endblock jquery %}
  {% block script %}
  {% endblock script %}

</body>

</html>

site_formation/templates/messages.html
<div class=" my-4 container">
    {% if messages %}

        {% for message in messages %}
                {% if message.tags == 'error' %}
                    <div class="alert alert-danger">
                        <p> {{ message }} </p>
                    </div>
                {% else %}
                    <div class="alert alert-success">
                        <p> {{ message }} </p>
                    </div>

                {% endif %}
        {% endfor %}

    {% endif %}
</div>

site_formation/templates/nav.html
<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home:home' %}">Gestion formations</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:home' %}">Accueil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'training:list_training'%}">Formations</a>
        </li>
        {% if not user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'sign_up' %}">Inscription</a>
        </li>
        {% endif %}
        {% if  user.is_authenticated and user.profile.user_type == 1 %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Espace étudiant
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
            <a class="dropdown-item" href="{% url 'edit_profile' %}">Editer profil</a>
            <a class="dropdown-item" href="{% url 'change_password' %}">Modifier mot de passe</a>
            <a class="dropdown-item" href="{% url 'training:my_training' %}">Mes formations</a>
          </div>
        </li>
        {% endif %}

        {% if  user.is_authenticated and user.profile.user_type == 2 %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Espace Formateur
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
            <a class="dropdown-item" href="{% url 'edit_profile' %}">Editer Profil</a>
            <a class="dropdown-item" href="{% url 'change_password' %}">Modifier mot de passe</a>
            <a class="dropdown-item" href="{% url 'teacher:courses_teacher' %}">Mes cours</a>
          </div>
        </li>
        {% endif %}

        {% if not user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Connexion</a>
        </li>
        {% endif %}

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Deconnexion</a>
        </li>
        {% endif %}
      </ul>

    </div>
  </div>
</nav>