site_formation/billing/urls.py
from django.urls import path, include
from .views import print_invoice



app_name='billing'

urlpatterns = [
    path('<int:id_session>/', print_invoice, name='print_invoice'),


    ]

site_formation/home/urls.py
from django.urls import path
from . import views


app_name='home'

urlpatterns = [
    path('',views.home,name='home'),

]

site_formation/site_formation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import  settings
from django.conf.urls.static import static


urlpatterns = [

    path('',include('home.urls')),
    path('training/',include('training.urls')),
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('billing/',include('billing.urls')),
    path('teacher/', include('teacher.urls')),
    path('payment/',include('payment.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

site_formation/training/urls.py
from django.urls import path
from . import views

app_name='training'

urlpatterns = [

    path('',views.TrainingListView.as_view(),name='list_training'),
    path('<int:id>/',views.training_detail,name='detail_training'),
    path('my_training/',views.my_training,name='my_training'),
    path('update_registration/<int:id_registration>/',views.update_registration,name='update_registration'),
]

site_formation/billing/models.py
from django.db import models
from django.contrib.auth.models import User
from training.models import Session
from account.models import Profile
from booking.models import RegistrationSession

# Create your models here.
class Invoice(models.Model):
    session=models.ForeignKey(Session,on_delete=models.SET_NULL,verbose_name='Session',null=True, blank=True)
    date=models.DateField(verbose_name='Date de facturation', null=True, auto_now=True)
    user=models.ForeignKey(User,verbose_name='Client',on_delete=models.SET_NULL,null=True, blank=True)
    STATUS = (
        (1, 'Payable'),
        (2, 'Payer'),
        (3, 'Annuler'),
    )

    status = models.PositiveSmallIntegerField(verbose_name='Statut', choices=STATUS, default=1)
    booking=models.ForeignKey(RegistrationSession, on_delete=models.SET_NULL,null=True, blank=True, verbose_name='Reservation')
    price=models.DecimalField(verbose_name='Prix',max_digits=6,decimal_places=2)

    class Meta:
        verbose_name='Facture'
        verbose_name_plural='Factures'

site_formation/training/models.py
from django.db import models
# Create your models here.
from account.models import Profile
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill





class Category(models.Model):
    name=models.CharField(verbose_name='nom de la catégorie',max_length=150)

    class Meta:
        verbose_name='Categorie'
        verbose_name_plural = 'Categories'


    def __str__(self):
        return self.name



class Training(models.Model):
    name=models.CharField(verbose_name='Nom de la formation', max_length=150)
    description=models.TextField(verbose_name='Description')
    price=models.DecimalField(verbose_name='Prix',max_digits=6,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE, verbose_name='Catégorie')
    number_hours=models.IntegerField(verbose_name='Nombre d''heures')
    image_training = models.ImageField(verbose_name='Image Formation',upload_to='training', blank=True)

    image_thumbnail = ImageSpecField(source='image_training',
                                      processors=[ResizeToFill(700, 400)],
                                      format='JPEG',
                                      options={'quality': 99})

    image_detail_thumbnail = ImageSpecField(source='image_training',
                                     processors=[ResizeToFill(900, 400)],
                                     format='JPEG',
                                     options={'quality': 99})



    class Meta:
        verbose_name='Formation'
        verbose_name_plural = 'Formations'

    def __str__(self):
        return self.name

class Session(models.Model):
    date_of_begin=models.DateField(verbose_name='Date de début',null=True)
    date_of_finish=models.DateField(verbose_name='Date de fin',null=True)
    seats_max=models.IntegerField(verbose_name='Nombre de places',null=True)
    training = models.ForeignKey(Training, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='Formateur',
                                limit_choices_to={'user_type': 2},default=2)
    full=models.BooleanField(verbose_name='Complet',default=False)







    class Meta:
        verbose_name='Session'
        verbose_name_plural = 'Sessions'







    def __str__(self):
        return 'Du '+ self.date_of_begin.strftime('%d/%m/%Y') + '  au  '\
               + self.date_of_finish.strftime('%d/%m/%Y') + '  '+self.training.__str__()

site_formation/training/forms.py
from django import forms
from .models import Session
from booking.models import RegistrationSession

class ChoiceSessionForm(forms.Form):
    sessions=forms.ModelChoiceField(queryset=Session.objects.all(),empty_label=None)

site_formation/training/views.py
from django.shortcuts import render,redirect
from django.views.generic.list import ListView
from .models import Training, Session
from django.shortcuts import get_object_or_404
from .forms import ChoiceSessionForm
from booking.models import RegistrationSession
from billing.models import Invoice
from account.models import Profile
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.contrib.auth.decorators import login_required



# Create your views here.





class TrainingListView(ListView):

    model = Training
    template_name = 'training/training_list.html'
    queryset = Training.objects.all()
'''
training_detail permet d'afficher le détail d'une formation
affiche les sessions de formations disponibles
permet de faire également une réservation de formation
permet de faire la création d"une facture une fois la réservation éffectuée.
'''
def training_detail(request,id):
    training=get_object_or_404(Training,id=id)

    if request.method=='POST':
        form_session=ChoiceSessionForm(request.POST)
        form_session.fields['sessions'].queryset = Session.objects.filter(training=id, full=False)

        if form_session.is_valid() and request.user.is_authenticated:
            session=form_session.cleaned_data['sessions']
            student=Profile.objects.get(user=request.user)

            if student.user_type == 1:

                if  not RegistrationSession.studentRegisterExist(session,student):
                    request.session['choice_session']=session
                    return redirect('payment:payment')

                else:
                    messages.error(request, 'Vous êtes déja inscrit à cette session !')
                    return redirect('training:list_training')

            else:
                messages.error(request, 'L\'inscription à une session est réservée à un étudiant inscrit !')
                return redirect('training:list_training')
        else:

            return redirect('login')

    else:

        form_session=ChoiceSessionForm()
        form_session.fields['sessions'].queryset = Session.objects.filter(training=id, full=False)


    context={'training':training,
             'form_session':form_session,
             }




    return render(request,'training/training_detail.html',context)

'''
La vue my_training va permettre d'afficher l'ensemble des réservations de formations pour
un utilisateur déterminé.
'''
@login_required(login_url='/account/login/')
def my_training(request):

    current_user=request.user.profile
    booking_user=RegistrationSession.objects.filter(student=current_user).exclude(status=3)
    return render(request,'training/my_training.html',{'booking_user':booking_user})

'''
La vue update_registration permet d'annuler une inscription elle prend 
comme paramètre request et l'id de l'inscription.
'''
@login_required(login_url='/account/login/')
def update_registration(request,id_registration):

    if request.method== 'POST':
        try:
            registration = RegistrationSession.objects.get(id=id_registration, student=request.user.profile)
            registration.status=3
            registration.save()

            # Annulation statut facture + remboursement du l'etudiant
            invoice=get_object_or_404(Invoice,booking=id_registration, user=request.user)
            invoice.status=3
            invoice.save()

        except ObjectDoesNotExist():
            messages.ERROR(request,"Votre formation n'a pas pu être annuler .")
            return redirect('training:my_training')

        messages.success(request, 'Votre inscription à bien été annuler .')
        return redirect('training:my_training')



    return redirect('training:my_training')

site_formation/training/templates/training/list_training.html
{% extends 'base.html' %}
{% block content %}

    {% include 'nav.html'%}
    <h4>Formations 2018-2019</h4>
    <ul>
        {% for training in object_list %}
            <li>{{ training }}</li>
        {% endfor %}
    </ul>
{% endblock content %}

site_formation/training/templates/training/my_training.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<style>
.row{
    min-height:460px;
}
</style>
<div class="container">
      {% if messages %}
        <div class="alert alert-info">
            {% for message in messages %}
                <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <div class="row">
        <div class="col-sm-12">
            <h4 class="my-4">Liste des inscriptions aux formations</h4>

            {% if not booking_user %}
                <p>Vous n'avez pas d'inscription ! </p>
            {% else %}

                <table class="table table-striped">
                      <thead>
                        <tr>
                          <th scope="col">N°</th>
                          <th scope="col">Formations</th>
                          <th scope="col">Date de début</th>
                          <th scope="col">Date de fin</th>
                          <th scope="col">Date d'inscription</th>
                          <th scope="col">Prix</th>
                          <th scope="col">Statut</th>
                          <th scope="col">Facture</th>
                          <th scope="col">Annulation</th>
                        </tr>
                      </thead>
                      <tbody>
                            {% for booking in booking_user  %}
                                <tr>
                                    <form class="update_status" method="POST" action="{% url 'training:update_registration' id_registration=booking.pk %}">
                                        {% csrf_token %}
                                        <td>{{booking.id}}</td>
                                        <td>{{booking.session.training.name}}</td>
                                        <td>{{booking.session.date_of_begin}}</td>
                                        <td>{{booking.session.date_of_finish}}</td>
                                        <td>{{booking.date_of_registration}}</td>
                                        <td>{{booking.session.training.price}} €</td>
                                        <td>{{booking.get_status_display}}</td>
                                        <td><a href="{% url 'billing:print_invoice' id_session=booking.session.pk %}">Facture</a></td>
                                        <td><input type="submit" class="btn btn-danger" value="Annuler"></td>

                                    </form>

                                </tr>

                            {% endfor%}
                      </tbody>
                </table>
            {% endif %}
        </div>


    </div>


</div>

{% endblock content %}

site_formation/training/templates/training/training_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}


<div class="container">
    <div class="row">
         <div class="col-lg-1">

         </div>
        <div class="col-lg-11">
             <div class="card mt-4">
                  <img class="card-img-top img-fluid" src="{{training.image_detail_thumbnail.url}}" alt="image_training">
                  <div class="card-body">
                    <h3 class="card-title">{{training.name}}</h3>

                    <p class="card-text">{{training.description}}</p>
                    <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
                    4.0
                  </div>
             </div>
             <div class="card card-outline-secondary my-4">
                  <div class="card-header">
                    Informations
                  </div>
                  <div class="card-body">

                    <h6><strong>Durée</strong></h6>
                    <p>{{training.number_hours}} heures</p>
                    <hr>
                    <h6><strong>Catégorie</strong></h6>
                    <p>{{training.category}}</p>
                    <hr>
                    <h6><strong>Prix</strong></h6>
                    <p>{{training.price|floatformat}} €</p>
                    <hr>
                    <h6><strong>Sessions</strong></h6>
                    <form class="choice_session" method="POST" action="">
                        {% csrf_token %}
                        {{form_session|crispy}}
                        <input type="submit" class="btn btn-success" value="S'inscrire">
                    </form>
                  </div>
            </div>

        </div>
    </div>


</div>





{% endblock content %}

site_formation/training/templates/training/training_list.html
{% extends 'base.html' %}
{% block content %}
{% include 'messages.html' %}
{% load static %}


 <h2 class=" my-4 text-left">Catalogue des formations</h2>

    <div class=" my-4 container mt-3">
        <div class="row">
            <div class="col"></div>
            <div class="col-sm center">
                <p><center>Rechercher une formation</center></p>
                <input class="form-control" id="myInput" type="text" placeholder="Recherche ...">
            </div>
            <div class="col"></div>
        </div>

            <div class="container mt-3">
            {% for training_one in object_list %}


                    <h5 class="my-4"> {{ training_one.category.name }} </h5>
                    {% for training in object_list %}
                        <ul class="list-group" id="list_training">
                        {% if training_one.category == training.category %}
                        <li class="list-group-item"><a href="{% url 'training:detail_training' id=training.pk %}">{{ training }}</a></li>
                        {% endif %}
                        </ul>
                    {% endfor %}

            {% endfor%}
            </div>
    </div>




{% endblock content %}

{% block script %}
<script src="{%static 'account/js/training_list.js'%}"></script>

{% endblock script %}